name: flutter_widget_guide
description: A flutter appliction listing all the widgets covered in Flutter widget of the week playlist.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.14+16

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #flutter_svg: ^0.14.0
  flutter_svg: 0.17.4
  url_launcher: ^5.1.6
  http: ^0.12.0+1
  youtube_player_flutter: ^6.1.1
  transparent_image: ^1.0.0
  package_info: ^0.4.0+6
  #firebase_core: 0.4.5
  #firebase_analytics: ^5.0.9
  #firebase_remote_config: ^0.3.0
  shared_preferences: ^0.5.3+4
  #firebase_messaging: ^6.0.9
  #firebase_admob: ^0.9.3+2
  provider: ^4.0.1

  line_icons: ^0.2.0
  flare_flutter: ^2.0.3
  flare_dart: ^2.3.4
  meta: ^1.0.5
  liquid_swipe: ^1.4.3
  font_awesome_flutter: ^8.8.1
  intl: ^0.16.1
  scoped_model: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/images/expanded_info.svg
      - assets/images/medium_icon.svg
      - assets/images/dp.png
      - assets/images/github.png
      - assets/images/linkedin.png
      - assets/images/twitter.png
      - assets/images/slack_icon.svg
      - assets/flutter_europe_white.png
      - assets/efe-kurnaz.jpg
      - assets/rodion-kutsaev.jpeg
      - assets/steve-johnson.jpeg      
      - assets/Teddy.flr
      - assets/adidas.png
      - assets/360.png
      - assets/cart.png
      - assets/images/apple.jpg
      - assets/images/artichoke.jpg
      - assets/images/asparagus.jpg
      - assets/images/avocado.jpg
      - assets/images/blackberry.jpg
      - assets/images/cantaloupe.jpg
      - assets/images/cauliflower.jpg
      - assets/images/endive.jpg
      - assets/images/fig.jpg
      - assets/images/grape.jpg
      - assets/images/green_bell_pepper.jpg
      - assets/images/habanero.jpg
      - assets/images/kale.jpg
      - assets/images/kiwi.jpg
      - assets/images/lemon.jpg
      - assets/images/lime.jpg
      - assets/images/mango.jpg
      - assets/images/mushroom.jpg
      - assets/images/nectarine.jpg
      - assets/images/persimmon.jpg
      - assets/images/plum.jpg
      - assets/images/potato.jpg
      - assets/images/radicchio.jpg
      - assets/images/radish.jpg
      - assets/images/squash.jpg
      - assets/images/strawberry.jpg
      - assets/images/tangelo.jpg
      - assets/images/tomato.jpg
      - assets/images/watermelon.jpg
      - assets/images/orange_bell_pepper.jpg
      - assets/img/
      - assets/icons/
      - assets/images/
      
  fonts:
      - family: Ubuntu
        fonts:
          - asset: assets/fonts/Ubuntu-Regular.ttf
      - family: Crimson
        fonts:
          - asset: assets/fonts/CrimsonText-Regular.ttf
      - family: SF Pro Display
        fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
      - family: IbarraRealNova
        fonts:
          - asset: assets/fonts/Ibarra_Real_Nova/IbarraRealNova-Regular.ttf
      - family: Deligne
        fonts:
          - asset: assets/fonts/OPTIDeligne-Normal.otf
      - family: RobotoMedium
        fonts:
          - asset: assets/fonts/Roboto-Medium.ttf
      - family: Product Sans
        fonts:
          - asset: assets/font/Product_Sans_Bold.ttf
          - asset: assets/font/Product_Sans_Regular.ttf
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins/Poppins-Medium.ttf
            weight: 600
          - asset: assets/fonts/Poppins/Poppins-Bold.ttf
            weight: 700
      - family: Montserrat-Bold
        fonts:
          - asset: assets/Montserrat-Bold.ttf

      - family: Montserrat-Medium
        fonts:
          - asset: assets/Montserrat-Medium.ttf

      - family: Montserrat-SemiBold
        fonts:
          - asset: assets/Montserrat-SemiBold.ttf
      - family: NotoSans
        fonts:
          - asset: assets/fonts/NotoSans-Regular.ttf
            weight: 400
          - asset: assets/fonts/NotoSans-Bold.ttf
            weight: 700
          - asset: assets/fonts/NotoSans-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/NotoSans-Italic.ttf
            style: italic
            weight: 400                      